// Generated by gencpp from file turtlebot_a1/MoveBotRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_A1_MESSAGE_MOVEBOTREQUEST_H
#define TURTLEBOT_A1_MESSAGE_MOVEBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace turtlebot_a1
{
template <class ContainerAllocator>
struct MoveBotRequest_
{
  typedef MoveBotRequest_<ContainerAllocator> Type;

  MoveBotRequest_()
    : vel()  {
    }
  MoveBotRequest_(const ContainerAllocator& _alloc)
    : vel(_alloc)  {
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _vel_type;
  _vel_type vel;




  typedef boost::shared_ptr< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBotRequest_

typedef ::turtlebot_a1::MoveBotRequest_<std::allocator<void> > MoveBotRequest;

typedef boost::shared_ptr< ::turtlebot_a1::MoveBotRequest > MoveBotRequestPtr;
typedef boost::shared_ptr< ::turtlebot_a1::MoveBotRequest const> MoveBotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_a1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'turtlebot_a1': ['/home/neeth/catkin_ws/src/turtlebot_a1/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7232eba0461d56f6b1172de04a9957ca";
  }

  static const char* value(const ::turtlebot_a1::MoveBotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7232eba0461d56f6ULL;
  static const uint64_t static_value2 = 0xb1172de04a9957caULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_a1/MoveBotRequest";
  }

  static const char* value(const ::turtlebot_a1::MoveBotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist vel\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::turtlebot_a1::MoveBotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveBotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_a1::MoveBotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_a1::MoveBotRequest_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_A1_MESSAGE_MOVEBOTREQUEST_H
