// Generated by gencpp from file turtlebot_a1/MoveBot.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_A1_MESSAGE_MOVEBOT_H
#define TURTLEBOT_A1_MESSAGE_MOVEBOT_H

#include <ros/service_traits.h>


#include <turtlebot_a1/MoveBotRequest.h>
#include <turtlebot_a1/MoveBotResponse.h>


namespace turtlebot_a1
{

struct MoveBot
{

typedef MoveBotRequest Request;
typedef MoveBotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveBot
} // namespace turtlebot_a1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_a1::MoveBot > {
  static const char* value()
  {
    return "15f94ffed970f2e1c99ad7dc815c974d";
  }

  static const char* value(const ::turtlebot_a1::MoveBot&) { return value(); }
};

template<>
struct DataType< ::turtlebot_a1::MoveBot > {
  static const char* value()
  {
    return "turtlebot_a1/MoveBot";
  }

  static const char* value(const ::turtlebot_a1::MoveBot&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_a1::MoveBotRequest> should match 
// service_traits::MD5Sum< ::turtlebot_a1::MoveBot > 
template<>
struct MD5Sum< ::turtlebot_a1::MoveBotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_a1::MoveBot >::value();
  }
  static const char* value(const ::turtlebot_a1::MoveBotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_a1::MoveBotRequest> should match 
// service_traits::DataType< ::turtlebot_a1::MoveBot > 
template<>
struct DataType< ::turtlebot_a1::MoveBotRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_a1::MoveBot >::value();
  }
  static const char* value(const ::turtlebot_a1::MoveBotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_a1::MoveBotResponse> should match 
// service_traits::MD5Sum< ::turtlebot_a1::MoveBot > 
template<>
struct MD5Sum< ::turtlebot_a1::MoveBotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_a1::MoveBot >::value();
  }
  static const char* value(const ::turtlebot_a1::MoveBotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_a1::MoveBotResponse> should match 
// service_traits::DataType< ::turtlebot_a1::MoveBot > 
template<>
struct DataType< ::turtlebot_a1::MoveBotResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_a1::MoveBot >::value();
  }
  static const char* value(const ::turtlebot_a1::MoveBotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_A1_MESSAGE_MOVEBOT_H
