// Generated by gencpp from file turtlebot_a1/Vel.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_A1_MESSAGE_VEL_H
#define TURTLEBOT_A1_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_a1
{
template <class ContainerAllocator>
struct Vel_
{
  typedef Vel_<ContainerAllocator> Type;

  Vel_()
    : status(0)  {
    }
  Vel_(const ContainerAllocator& _alloc)
    : status(0)  {
    }



   typedef int64_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::turtlebot_a1::Vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_a1::Vel_<ContainerAllocator> const> ConstPtr;

}; // struct Vel_

typedef ::turtlebot_a1::Vel_<std::allocator<void> > Vel;

typedef boost::shared_ptr< ::turtlebot_a1::Vel > VelPtr;
typedef boost::shared_ptr< ::turtlebot_a1::Vel const> VelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_a1::Vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_a1::Vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_a1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'turtlebot_a1': ['/home/neeth/catkin_ws/src/turtlebot_a1/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_a1::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_a1::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_a1::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_a1::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_a1::Vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_a1::Vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_a1::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4107476a6271fc2684d94be17d33f854";
  }

  static const char* value(const ::turtlebot_a1::Vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4107476a6271fc26ULL;
  static const uint64_t static_value2 = 0x84d94be17d33f854ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_a1::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_a1/Vel";
  }

  static const char* value(const ::turtlebot_a1::Vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_a1::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 status\n\
";
  }

  static const char* value(const ::turtlebot_a1::Vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_a1::Vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_a1::Vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_a1::Vel_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int64_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_A1_MESSAGE_VEL_H
