// Generated by gencpp from file neeth_tbot/Command.msg
// DO NOT EDIT!


#ifndef NEETH_TBOT_MESSAGE_COMMAND_H
#define NEETH_TBOT_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <neeth_tbot/CommandRequest.h>
#include <neeth_tbot/CommandResponse.h>


namespace neeth_tbot
{

struct Command
{

typedef CommandRequest Request;
typedef CommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Command
} // namespace neeth_tbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::neeth_tbot::Command > {
  static const char* value()
  {
    return "304dd3f6ef6b49ed507d4f75dde10aeb";
  }

  static const char* value(const ::neeth_tbot::Command&) { return value(); }
};

template<>
struct DataType< ::neeth_tbot::Command > {
  static const char* value()
  {
    return "neeth_tbot/Command";
  }

  static const char* value(const ::neeth_tbot::Command&) { return value(); }
};


// service_traits::MD5Sum< ::neeth_tbot::CommandRequest> should match 
// service_traits::MD5Sum< ::neeth_tbot::Command > 
template<>
struct MD5Sum< ::neeth_tbot::CommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::neeth_tbot::Command >::value();
  }
  static const char* value(const ::neeth_tbot::CommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::neeth_tbot::CommandRequest> should match 
// service_traits::DataType< ::neeth_tbot::Command > 
template<>
struct DataType< ::neeth_tbot::CommandRequest>
{
  static const char* value()
  {
    return DataType< ::neeth_tbot::Command >::value();
  }
  static const char* value(const ::neeth_tbot::CommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::neeth_tbot::CommandResponse> should match 
// service_traits::MD5Sum< ::neeth_tbot::Command > 
template<>
struct MD5Sum< ::neeth_tbot::CommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::neeth_tbot::Command >::value();
  }
  static const char* value(const ::neeth_tbot::CommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::neeth_tbot::CommandResponse> should match 
// service_traits::DataType< ::neeth_tbot::Command > 
template<>
struct DataType< ::neeth_tbot::CommandResponse>
{
  static const char* value()
  {
    return DataType< ::neeth_tbot::Command >::value();
  }
  static const char* value(const ::neeth_tbot::CommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NEETH_TBOT_MESSAGE_COMMAND_H
