// Generated by gencpp from file neeth_tbot/CommandRequest.msg
// DO NOT EDIT!


#ifndef NEETH_TBOT_MESSAGE_COMMANDREQUEST_H
#define NEETH_TBOT_MESSAGE_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace neeth_tbot
{
template <class ContainerAllocator>
struct CommandRequest_
{
  typedef CommandRequest_<ContainerAllocator> Type;

  CommandRequest_()
    : cmd()  {
    }
  CommandRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _cmd_type;
  _cmd_type cmd;




  typedef boost::shared_ptr< ::neeth_tbot::CommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neeth_tbot::CommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommandRequest_

typedef ::neeth_tbot::CommandRequest_<std::allocator<void> > CommandRequest;

typedef boost::shared_ptr< ::neeth_tbot::CommandRequest > CommandRequestPtr;
typedef boost::shared_ptr< ::neeth_tbot::CommandRequest const> CommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neeth_tbot::CommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neeth_tbot::CommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neeth_tbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neeth_tbot::CommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neeth_tbot::CommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neeth_tbot::CommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0c47a2b42626c8e0bd2a277053c6c62";
  }

  static const char* value(const ::neeth_tbot::CommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0c47a2b42626c8eULL;
  static const uint64_t static_value2 = 0x0bd2a277053c6c62ULL;
};

template<class ContainerAllocator>
struct DataType< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neeth_tbot/CommandRequest";
  }

  static const char* value(const ::neeth_tbot::CommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist cmd\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::neeth_tbot::CommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neeth_tbot::CommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neeth_tbot::CommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEETH_TBOT_MESSAGE_COMMANDREQUEST_H
