// Generated by gencpp from file neeth_tbot/CommandResponse.msg
// DO NOT EDIT!


#ifndef NEETH_TBOT_MESSAGE_COMMANDRESPONSE_H
#define NEETH_TBOT_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neeth_tbot
{
template <class ContainerAllocator>
struct CommandResponse_
{
  typedef CommandResponse_<ContainerAllocator> Type;

  CommandResponse_()
    : ok(0)  {
    }
  CommandResponse_(const ContainerAllocator& _alloc)
    : ok(0)  {
    }



   typedef int64_t _ok_type;
  _ok_type ok;




  typedef boost::shared_ptr< ::neeth_tbot::CommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neeth_tbot::CommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandResponse_

typedef ::neeth_tbot::CommandResponse_<std::allocator<void> > CommandResponse;

typedef boost::shared_ptr< ::neeth_tbot::CommandResponse > CommandResponsePtr;
typedef boost::shared_ptr< ::neeth_tbot::CommandResponse const> CommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neeth_tbot::CommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neeth_tbot::CommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neeth_tbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neeth_tbot::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neeth_tbot::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neeth_tbot::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffe45f316ca87fa4adf13cb9d40744eb";
  }

  static const char* value(const ::neeth_tbot::CommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffe45f316ca87fa4ULL;
  static const uint64_t static_value2 = 0xadf13cb9d40744ebULL;
};

template<class ContainerAllocator>
struct DataType< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neeth_tbot/CommandResponse";
  }

  static const char* value(const ::neeth_tbot::CommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ok\n\
\n\
";
  }

  static const char* value(const ::neeth_tbot::CommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neeth_tbot::CommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neeth_tbot::CommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEETH_TBOT_MESSAGE_COMMANDRESPONSE_H
